[target.thumbv7em-none-eabi]
runner = "probe-rs run --chip STM32H723ZG --connect-under-reset"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabi"
